setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
eminer.exe -S clona.ru:5087  -U YOUR_WALLETID_HERE -P x -N rig3 --cloud-key GENERATE_AT_CLOUD.EMINER.NET
